appId: com.geraldy.macrozone
---
- launchApp
- extendedWaitUntil:
    visible: "nutriFlow|Recent Meals|Repas récents"
    timeout: 20000
- tapOn:
    id: "settings-tab"
- tapOn:
    id: "language-fr"
- tapOn:
    id: "home-tab"
- assertVisible: "Accueil"
- tapOn:
    id: "settings-tab"
- tapOn:
    id: "language-en"
- tapOn:
    id: "home-tab"
- assertVisible: "Home"